# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity_basic_env.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unity_basic_env.proto',
  package='unitybasicenv',
  syntax='proto3',
  serialized_options=b'\n\035io.grpc.examples.unitbasicenvB\022UnityBasicEnvProtoP\001\242\002\003UBE',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15unity_basic_env.proto\x12\runitybasicenv\"U\n\x11UnityBasicEnvNote\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tactionObs\x18\x02 \x01(\x05\x12\x0e\n\x06reward\x18\x03 \x01(\x02\x12\x0c\n\x04\x64one\x18\x04 \x01(\x08\x32n\n\rUnityBasicEnv\x12]\n\x11UnityBasicEnvChat\x12 .unitybasicenv.UnityBasicEnvNote\x1a .unitybasicenv.UnityBasicEnvNote\"\x00(\x01\x30\x01\x42;\n\x1dio.grpc.examples.unitbasicenvB\x12UnityBasicEnvProtoP\x01\xa2\x02\x03UBEb\x06proto3'
)




_UNITYBASICENVNOTE = _descriptor.Descriptor(
  name='UnityBasicEnvNote',
  full_name='unitybasicenv.UnityBasicEnvNote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='unitybasicenv.UnityBasicEnvNote.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actionObs', full_name='unitybasicenv.UnityBasicEnvNote.actionObs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward', full_name='unitybasicenv.UnityBasicEnvNote.reward', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='done', full_name='unitybasicenv.UnityBasicEnvNote.done', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['UnityBasicEnvNote'] = _UNITYBASICENVNOTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnityBasicEnvNote = _reflection.GeneratedProtocolMessageType('UnityBasicEnvNote', (_message.Message,), {
  'DESCRIPTOR' : _UNITYBASICENVNOTE,
  '__module__' : 'unity_basic_env_pb2'
  # @@protoc_insertion_point(class_scope:unitybasicenv.UnityBasicEnvNote)
  })
_sym_db.RegisterMessage(UnityBasicEnvNote)


DESCRIPTOR._options = None

_UNITYBASICENV = _descriptor.ServiceDescriptor(
  name='UnityBasicEnv',
  full_name='unitybasicenv.UnityBasicEnv',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=127,
  serialized_end=237,
  methods=[
  _descriptor.MethodDescriptor(
    name='UnityBasicEnvChat',
    full_name='unitybasicenv.UnityBasicEnv.UnityBasicEnvChat',
    index=0,
    containing_service=None,
    input_type=_UNITYBASICENVNOTE,
    output_type=_UNITYBASICENVNOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UNITYBASICENV)

DESCRIPTOR.services_by_name['UnityBasicEnv'] = _UNITYBASICENV

# @@protoc_insertion_point(module_scope)
