# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import unity_basic_env_pb2 as unity__basic__env__pb2


class UnityBasicEnvStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnityBasicEnvChat = channel.stream_stream(
                '/unitybasicenv.UnityBasicEnv/UnityBasicEnvChat',
                request_serializer=unity__basic__env__pb2.UnityBasicEnvNote.SerializeToString,
                response_deserializer=unity__basic__env__pb2.UnityBasicEnvNote.FromString,
                )


class UnityBasicEnvServicer(object):
    """Interface exported by the server.
    """

    def UnityBasicEnvChat(self, request_iterator, context):
        """A Bidirectional streaming RPC.

        Accepts a stream of UnityBasicEnvNote sent while a route is being traversed,
        while receiving other UnityBasicEnvNote (e.g. from other users).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnityBasicEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnityBasicEnvChat': grpc.stream_stream_rpc_method_handler(
                    servicer.UnityBasicEnvChat,
                    request_deserializer=unity__basic__env__pb2.UnityBasicEnvNote.FromString,
                    response_serializer=unity__basic__env__pb2.UnityBasicEnvNote.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unitybasicenv.UnityBasicEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnityBasicEnv(object):
    """Interface exported by the server.
    """

    @staticmethod
    def UnityBasicEnvChat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/unitybasicenv.UnityBasicEnv/UnityBasicEnvChat',
            unity__basic__env__pb2.UnityBasicEnvNote.SerializeToString,
            unity__basic__env__pb2.UnityBasicEnvNote.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
